# Generated by Django 5.2.4 on 2025-07-21 04:04

import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(default=users.models.default_background, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=users.models.default_profile, upload_to='avatar/'),
        ),
    ]
