# Generated by Django 5.2.4 on 2025-08-01 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_background_image_customuser_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='users_blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
