# Generated by Django 5.2.4 on 2025-08-12 03:23

import cloudinary.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=users.models.default_background, max_length=255, null=True, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=users.models.default_profile, max_length=255, null=True, verbose_name='profile'),
        ),
    ]
