# Generated by Django 5.2.4 on 2025-08-12 03:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_background_qnntrv', max_length=255, null=True, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar_iq42sm', max_length=255, null=True, verbose_name='profile'),
        ),
    ]
